[markup]
[markup.highlight]
    lineNos = true
    tabWidth = 4
    noClasses = false
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
    enable = true
[markup.goldmark.extensions.passthrough.delimiters]
    block = [['$$', '$$']]
    inline = [['$', '$']]

[outputFormats]
[outputFormats.rss]
    baseName = "rss"
    isHTML = false
    isPlainText = false
    mediaType = "application/rss+xml"
    noUgly = true
    permalinkable = false
    rel = "alternate"

[module]
[module.hugoVersion]
    extended = true
    min = "0.158.0"
