baseURL = 'https://www.tifrueh.ch/'
languageCode = 'en-GB'
title = 'Timo Früh'
copyright = 'All work is licensed under CC BY-SA 4.0, unless stated otherwise.'
defaultContentLanguage = 'en'
pluralizeListTitles = false
disableKinds = [ 'taxonomy', 'term' ]

[permalinks]
[permalinks.page]
    blog = '/blog/:year/:month/:slug'

[markup]
[markup.highlight]
    lineNos = false
    tabWidth = 4
    noClasses = false

[frontmatter]
publishDate = [ 'date', 'publishDate' ]

[params]
[params.author]
    name = "Timo Früh"

[outputs]
home = [ 'html', 'rss' ]
section = [ 'html' ]

[outputFormats]
[outputFormats.rss]
    baseName = "rss"
    isHTML = false
    isPlainText = false
    mediaType = "application/rss+xml"
    noUgly = true
    permalinkable = false
    rel = "alternate"

[menus]
[[menus.main]]
    name = '/about'
    pageRef = '/about'
    weight = 10
[[menus.main]]
    name = '/blog'
    pageRef = '/blog'
    weight = 20
[[menus.main]]
    name = '/explore'
    pageRef = '/explore'
    weight = 30
